### ISSUE TITLE
Contoh user untuk demo agar bisa membuka aplikasi

### ISSUE THREAD

**Issue by aephidayatuloh** [rizkynurhambali/sipp-binaans#3]
Saya boleh minta username dan password untuk membuka app ini?

**Comment by rizkynurhambali** [comment]
Untuk username dan password bisa gunakan daftar berikut Pak.
username (password): admin(admin), sr(sr), kestari(kestari).

Namun, ketiganya masih tertaut dengan role yang sama, jadi belum ada perbedaan. Terima kasih.

**Comment by aephidayatuloh** [comment]
Terima kasih
